# Generated by Django 5.1.3 on 2024-11-28 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_vocabulary_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_questions', models.IntegerField(default=10)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab.category')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_results', to='vocab.testresult')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.vocabulary')),
            ],
        ),
    ]
